import { NextRequest, NextResponse } from "next/server";
import { getItemById } from "@/lib/db/queries/items";
import { jsPDF } from "jspdf";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const item = await getItemById(parseInt(id));
  if (!item) {
    return NextResponse.json({ error: "Item not found" }, { status: 404 });
  }

  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Amy's Finds - Item Details", margin, y);
  y += 12;

  // Divider
  doc.setDrawColor(59, 122, 87);
  doc.setLineWidth(0.5);
  doc.line(margin, y, 190, y);
  y += 10;

  // Title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(item.title, margin, y);
  y += 8;

  // Price
  if (item.price_range) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(59, 122, 87);
    doc.text(`Price Range: ${item.price_range}`, margin, y);
    doc.setTextColor(0, 0, 0);
    y += 10;
  }

  // Description
  if (item.description) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Description", margin, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    const descLines = doc.splitTextToSize(item.description, 170);
    doc.text(descLines, margin, y);
    y += descLines.length * 5 + 8;
  }

  // Condition Notes
  if (item.condition_notes) {
    doc.setFont("helvetica", "bold");
    doc.text("Condition Notes", margin, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    const condLines = doc.splitTextToSize(item.condition_notes, 170);
    doc.text(condLines, margin, y);
    y += condLines.length * 5 + 8;
  }

  // Refinishing Tips
  if (item.refinishing_tips) {
    doc.setFont("helvetica", "bold");
    doc.text("Refinishing Tips", margin, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    const tipLines = doc.splitTextToSize(item.refinishing_tips, 170);
    doc.text(tipLines, margin, y);
    y += tipLines.length * 5 + 8;
  }

  // Key Features
  if (item.key_features && item.key_features.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.text("Key Features", margin, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    item.key_features.forEach((feature) => {
      doc.text(`• ${feature}`, margin + 4, y);
      y += 5;
    });
    y += 4;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(
    `Generated by Amy's Finds | ${new Date().toLocaleDateString()}`,
    margin,
    285
  );

  const pdfBuffer = Buffer.from(doc.output("arraybuffer"));

  return new NextResponse(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="amys-finds-item-${item.id}.pdf"`,
    },
  });
}
